### PR TITLE
fix compile error with bench

### PR DESCRIPTION
**Pull request by bftjoe**

### CODE REVIEW

**Comment by bftjoe** [comment]
Maybe wrong version of picobench is pinned to repo? I looked at the other pull request.

**Comment by rafaelkallis** [comment]
Thanks for your time and effort. I've done some work myself, could you check if the latest commit in the master branch works fine for you now?

**Comment by bftjoe** [comment]
It does not work for me - compile error with MSVC 2019

cl : command line error D8021: invalid numeric argument '/Wextra'

**Comment by rafaelkallis** [comment]
you could try fiddling with the cmake settings here https://github.com/rafaelkallis/adaptive-radix-tree/blob/master/CMakeLists.txt#L8

**Pull request closed without merging**
